networkmanager: Workaround docs builder not finding GIRepository 2.0
The build started to fail for some reason, even though the `gobject-introspection`’s typelibdir (which contains the 2.0) is on `GI_TYPELIB_PATH`:

	[479/927] Generating src/libnm-client-impl/nm-settings-docs-gir-nmcli.xml with a custom command (wrapped by meson because command contains newlines)
	FAILED: src/libnm-client-impl/nm-settings-docs-gir-nmcli.xml
	/nix/store/lxfiv4rqwv2q1svgpb47jy1wja9v2hdq-meson-1.7.0/bin/meson --internal exe --unpickle /build/NetworkManager-1.50.2/build/meson-private/meson_exe_env_484c8f0547bf97b34e0ba74b072f480e440ec8b4.dat
	while executing ['/nix/store/fr9yr63a1267cr0r86w18c77mh3xavcc-coreutils-9.6/bin/env', 'GI_TYPELIB_PATH=/build/NetworkManager-1.50.2/build/src/libnm-client-impl:/nix/store/50057srf0sz09f3klcras78867wk3sfz-glib-2.84.0/lib/girepository-1.0:/nix/store/x47f69xz73vqbf56ndmwxwbvlifjs5nd-gobject-introspection-wrapped-1.83.4/lib/girepository-1.0:/nix/store/w33j43hpxdwzrz9mbscrrp5z2brafm6h-gobject-introspection-1.83.4/lib/girepository-1.0:/nix/store/dxgfk5l6j2ai19dv91cd3g64gllsm4xw-polkit-124/lib/girepository-1.0:/nix/store/y8gsv098vxcshlghjv7ni3rv0dkn9y14-modemmanager-1.22.0/lib/girepository-1.0:/nix/store/1nl72sch8iwir6vijh9v8d1i0zd0nccy-libsoup-2.74.3/lib/girepository-1.0\n', 'LD_LIBRARY_PATH=/build/NetworkManager-1.50.2/build/src/libnm-client-impl', '/build/NetworkManager-1.50.2/tools/generate-docs-nm-settings-docs-gir.py', '--lib-path', '/build/NetworkManager-1.50.2/build/src/libnm-client-impl', '--gir', 'src/libnm-client-impl/NM-1.0.gir', '--output', 'src/libnm-client-impl/nm-settings-docs-gir-nmcli.xml', '--target', 'nmcli']
	--- stdout ---

	--- stderr ---
	Traceback (most recent call last):
	  File "/build/NetworkManager-1.50.2/tools/generate-docs-nm-settings-docs-gir.py", line 13, in <module>
	    gi.require_version("GIRepository", "2.0")
	  File "/nix/store/9qqqhiz2dagrgj89ixwdwxx6v89dwxsn-python3-3.12.9-env/lib/python3.12/site-packages/gi/__init__.py", line 132, in require_version
	    raise ValueError('Namespace %s not available for version %s' %
	ValueError: Namespace GIRepository not available for version 2.0

This patch works around it by no longer attempting to manipulate GIRepository explicitly, and instead using `GI_TYPELIB_PATH`.

Verified that the produced docs look the same as on nixos-unstable after applying this patch, except that default values are now listed where they were previously empty. But that is probably result of some unrelated GI change.